### ISSUE TITLE
java.lang.NoSuchMethodError : Getting crash when i start idetification

### ISSUE THREAD

**Issue by trupti237** [ondato/ondato-sdk-android#11]
i implemented this sdk in my android project but when i init and then startIdentification call app will be crash and this is the error showing in my logcat

"java.lang.NoSuchMethodError: No static method bind(Lkotlin/Pair;Lkotlin/reflect/KClass;)Lkotlin/Pair; in class Lorg/koin/dsl/DefinitionBindingKt; or its super classes (declaration of 'org.koin.dsl.DefinitionBindingKt' appears in /data/app/com.app.plutope-jsSnOe3TyLQKnFYsm93Y7w==/base.apk!classes23.dex)"

SS : https://prnt.sc/X2IUIGJr_XXu

and here is the ss of code i implement as per sdk integration : https://prnt.sc/HCLhd3Y4S3ma

**Comment by Svaike** [comment]
@trupti237 which SDK version are you using? Have you tried the example app?

**Comment by edgaras-simanavicius** [comment]
This is probably caused by the koin dependency not being backwards compatible. If you have the option, try to downgrade to kotlin 1.6.21 and koin 3.2.4. We are working on a version with better compatibility.

**Comment by Svaike** [comment]
@trupti237 the latest SDK version (2.5.6) should resolve the issue
