### ISSUE TITLE
java.lang.NoSuchMethodError: No static method bind

### ISSUE THREAD

**Issue by BuildThingsWithPravin** [ondato/ondato-sdk-android#12]
getting crash when i click init with ID and than startIdentification 

"java.lang.NoSuchMethodError: No static method bind(Lkotlin/Pair;Lkotlin/reflect/KClass;)Lkotlin/Pair; in class Lorg/koin/dsl/DefinitionBindingKt; or its super classes (declaration of 'org.koin.dsl.DefinitionBindingKt' appears in /data/app/com.app.xyz-jsSnOe3TyLQKnFYsm93Y7w==/base.apk!classes23.dex)"

![image](https://github.com/ondato/ondato-sdk-android/assets/136877196/154e52fc-4a19-49ef-a7e6-b7416979dd68)

**Comment by Svaike** [comment]
@BuildThingsWithPravin which SDK version are you using?

**Comment by BuildThingsWithPravin** [comment]
latest versin : implementation("com.kyc.ondato:sdk:2.5.4")

**Comment by Svaike** [comment]
Have you tried the example app?

**Comment by BuildThingsWithPravin** [comment]
Yes i am trying with example app and apply same code in my project getting crash..witch i send ss..

**Comment by BuildThingsWithPravin** [comment]
![image](https://github.com/ondato/ondato-sdk-android/assets/136877196/3ff2758b-11d1-43e5-aee6-313ba7b30717)

here is an implementation of code..

**Comment by udayvhits** [comment]
Facing same issue 

@Svaike  or team OnDato any update on this issue..  i am created demo project for this issue please check once : https://github.com/udayvhits/OnDatoDemo

**Comment by edgaras-simanavicius** [comment]
This is probably caused by the koin dependency not being backwards compatible. If you have the option, try to downgrade to kotlin 1.6.21 and koin 3.2.4. We are working on a version with better compatibility.

**Comment by mrbarnk** [comment]
I have downgraded to 3.2.4, same error.
but looks like 1.6.21 doesnt exist so I couldnt try that.
![image](https://github.com/ondato/ondato-sdk-android/assets/37006356/f8384605-dead-49b7-a817-c94db420de83)
Error
![image](https://github.com/ondato/ondato-sdk-android/assets/37006356/a7082878-dba1-4a51-a3b9-df27798ac011)

**Comment by Svaike** [comment]
@BuildThingsWithPravin the latest SDK version should resolve the issue with Kotlin
