### ISSUE TITLE
java.lang.NoSuchMethodError: No static method bind

### ISSUE THREAD

**Issue by udayvhits** [ondato/ondato-sdk-android#13]
Getting crash app when i implement this SDK 
"java.lang.NoSuchMethodError: No static method bind(Lkotlin/Pair;Lkotlin/reflect/KClass;)Lkotlin/Pair; in class Lorg/koin/dsl/DefinitionBindingKt; or its super classes (declaration of 'org.koin.dsl.DefinitionBindingKt' appears in /data/app/~~aKsXJjHANC5Wem2CqYEkKg==/com.example.kycdemo-Q7k7O-NB7_9FPhVwn_1YFQ==/base.apk!classes10.dex)"

this is the error right now i am facing 
![image](https://github.com/ondato/ondato-sdk-android/assets/170944318/47105140-3779-48d2-b67a-168867ae3337)

here is my project implementation demo project link where i am getting the crash when start identification : https://github.com/udayvhits/OnDatoDemo

Can you please identify what i am doing wrong..

**Comment by edgaras-simanavicius** [comment]
This is probably caused by the koin dependency not being backwards compatible. If you have the option, try to downgrade to kotlin 1.6.21 and koin 3.2.4. We are working on a version with better compatibility.

**Comment by Svaike** [comment]
@udayvhits the latest SDK version should resolve the issue
