### ISSUE TITLE
FOREGROUND_SERVICE_MEDIA_PROJECTION causing playstore to reject updates

### ISSUE THREAD

**Issue by HansCraftsman** [ondato/ondato-sdk-android#14]
**Version of the ondato-sdk-android**
2.5.4

Platforms - Android

**Steps to reproduce**
Build appbundle
Upload to Google Play
Gets rejected

**Expected results**
We only use the document verification service. How do I disable FOREGROUND_SERVICE_MEDIA_PROJECTION from the manifest?
**Actual results**
FOREGROUND_SERVICE_MEDIA_PROJECTION causing playstore to reject updates.

After updating the SDK for Flutter to version 0.5.0 (internal package ondato-sdk-android 2.5.4), Android apps are rejected by Google Play and require you to explain the use of **android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION** and send a video using this service.

Is it possible to put the use of a function using **android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION** in a separate module so that it can be excluded using a similar construction:

```
// build.gradle (project-level)

//...

configurations.configureEach {
 exclude group: "com.kyc.ondato.ondato_flutter", module: "module_using_foreground_service_permission"
}
```

**Comment by Svaike** [comment]
Hi, added demo file to integration documentation that you can download and share with play store: https://ondato.atlassian.net/wiki/spaces/PUB/pages/2334359560/Customer+onboarding+KYC+mobile+SDK+integration#Google-Play-Store-rejection

let me know if it resolves your issue with them

**Comment by Svaike** [comment]
The mentioned service's purpose is to record the identity verification process for the cases where local authorities require it. If it's running for the specific application it is controlled via API configuration.

If you send me the info (svajunas.gaina@ondato.com) about the client that uses SDK, then I will check if this functionality is enabled for your use case.

**Comment by HansCraftsman** [comment]
Thanks, let's try it.
Is it normal that the video uses ios graphics, not android?

**Comment by Svaike** [comment]
We'll prepare the demo flow with Android graphics if it does not go through. There was another similar case with Play Store and it was sufficient to provide this demo.

**Comment by HansCraftsman** [comment]
hi, Google is rejecting the release, it doesn't have enough arguments from the video. They want exactly how the **FOREGROUND_SERVICE_MEDIA_PROJECTION** service is used.
Here is their answer:

> Issue found: Play Console declaration and/or app description in Google Play Store does not sufficiently demonstrate the use of permission.
> 
> We are unable to approve your app’s use of [FOREGROUND_SERVICE](https://notifications.google.com/g/p/ANiao5pfu8OIuN0006SpXQrjyqz5UB_x_tGrbN-yEHRg9cM1G1-iJCvsU_6_iaYCY-_GXbvPpdk3RotmOw63Z34z2-SL5nZsSZ64QYOMguBVQc0uZBoKsNJky1LmV5Up-i8q0kvOl5bGRWYg_dgigEfxKR2BmI1B2ceFTrPfmoFLHP69d1hMDvL3PHZtAZjagy26n64lI6WgB7XRC-ckzOnusnsFaKJZYw353EU1jJT7OrbolY0oGyMnb5c7OwC3nnBef4jJgmi37IZtFXK7DxybIQ) permission because we found the following information provided to be insufficient in evaluating compliance with [foreground service permission requirements](https://notifications.google.com/g/p/ANiao5pbWq0WwcBBHBmN_CiaWsZgOb3DSv3exrYuZdSZuS0jBhNtK-a9nCuvXiTbY2bhMteK8AAysBjyxxaXc6FTAiU668g6J6qNIrQbNMwkrSrXtx7zX5S1znYshGI6SCWo1QV_62XAW6_AR4ua-G9qKQ_CpaRBjnVL-kPJDnea9ep_X-NqsvSw999mMX34wwBTVrQODUML8mlgOQLqaaTNLBu6HEv7nDZe6TcF7g9gz-_NbgD3TXwmbpE0zi_yDxxUcpwodu1hDuSfkTwvyDPrmgUj_GlH23mI3_dXoHt0RFmz5JE):
> 
> The video link you provided in the Play Console declaration and/or
> The app description in the Google Play store.
> 
> Issue details
> 
> We found an issue in the following area(s):
> 
> Version code 604
> Version code 2067708
> 
> To bring your app into compliance, follow these steps:
> 

- > Please verify that the version of the app submitted for review is working as intended and that the app description on the Google Play Store accurately reflects the core functionality that requires the use of [foreground service permission](https://notifications.google.com/g/p/ANiao5o3zwXl6BhflmzjqPcob-wuwW7AO81v8afJ_dCd1aOis4j0sFQA4haFII5HDfC94xTtnqW5xlKIyBrQDGUp1tUhylbxSgR1J_ESK4ytL2UXdp1vQ8fh06e0g2MMPpfgmgp9gz3zUu61zWbCpfzlShCG9cT-Z9TmMfzm6VEfWBG1vIuQPR_7abDWLecxKtbbnnH3l5CdPCE3rI8Q7YPREDTPsYkDCeQXqJaBTn1u78znAgat73kwg-6cn4GxZ7xOsvQvnQ).
- > Submit an [updated declaration](https://notifications.google.com/g/p/ANiao5rWrJ02Wah4mXFvFGleswZfCpb9g8sy764bOc7l5P6P7GY48c43Z7nBVYS90jEsWDPpqpPZ_G45D2mM65PV5hGCdkG_PpTAsQ0_zOYjE6dLPim2l_-4Xwac5EVU0yPHtST0kzzPp3qWbSEpCuvjYsaNgYG-4J2o_GBlWAHBjg8L946uA2RALJEIhdB5bquFATbjcTy9181evaV4DaLMiMcewjDtSzVIql5OLwf08uAZIDnXsN7XFeMTYuflCglUyiDSz4hpdOA) with clear and relevant video demonstrating the core feature’s dependency on the [foreground service permission](https://notifications.google.com/g/p/ANiao5o3zwXl6BhflmzjqPcob-wuwW7AO81v8afJ_dCd1aOis4j0sFQA4haFII5HDfC94xTtnqW5xlKIyBrQDGUp1tUhylbxSgR1J_ESK4ytL2UXdp1vQ8fh06e0g2MMPpfgmgp9gz3zUu61zWbCpfzlShCG9cT-Z9TmMfzm6VEfWBG1vIuQPR_7abDWLecxKtbbnnH3l5CdPCE3rI8Q7YPREDTPsYkDCeQXqJaBTn1u78znAgat73kwg-6cn4GxZ7xOsvQvnQ).
- > Make any necessary corrections or modifications to meet the policy requirement.
- > Ensure [valid testing credentials](https://notifications.google.com/g/p/ANiao5qbJUqVkR0dzVx6itIuMjkK-9PHbd-In-5XSwzpAJ8QjLa1YhSOzMmxdM2-VpKlvWTaZv9WLUSoCf9EgTYItGtCxyMfL6v_gLuSw1sCOErWwujWWABRxhh2ve8CPYKBueytHEr8xdBeSEIMriLp0WDI2ZTWbVLHmzxrN6KfS32vgNZlWNe4F5dTrI_hX9aIObfgJ8BsCICeSUqWArVGTOCNreUKNgu8f8txVbN4Gb9W3giEvr70KHyXd8opIK4fMZKMjoyHziI) are provided.
- > About the Permissions for Foreground Services

> 
> The Foreground Service permission ensures the appropriate use of user-facing foreground services. For apps targeting Android 14 and above, you must specify a valid foreground service type for each foreground service used in your app, and declare the foreground service permission that is appropriate for that type. For example, if your app’s use case requires map geolocation, you must declare the FOREGROUND_SERVICE_LOCATION permission in your app’s manifest.
> 
> With the exceptions of systemExempted and shortService foreground service types, apps are only allowed to declare a foreground service permission if the use:

- > Provides a feature that is beneficial to the user and relevant to the core functionality of the app.
- > Is initiated by the user or is user perceptible (for example, audio from playing a song, cast media to another device, accurate and clear user notification, user request to upload a photo to the cloud).
- > Can be terminated or stopped by the user.
- > Can’t be interrupted or deferred by the system without causing a negative user experience or causing the user anticipated feature to not work as intended (for example, a phone call needs to start immediately and can’t be deferred by the system).
- > Runs only for as long as necessary to complete the task.

> The use of foreground service is further explained on this [Play Console Help Center](https://notifications.google.com/g/p/ANiao5pbWq0WwcBBHBmN_CiaWsZgOb3DSv3exrYuZdSZuS0jBhNtK-a9nCuvXiTbY2bhMteK8AAysBjyxxaXc6FTAiU668g6J6qNIrQbNMwkrSrXtx7zX5S1znYshGI6SCWo1QV_62XAW6_AR4ua-G9qKQ_CpaRBjnVL-kPJDnea9ep_X-NqsvSw999mMX34wwBTVrQODUML8mlgOQLqaaTNLBu6HEv7nDZe6TcF7g9gz-_NbgD3TXwmbpE0zi_yDxxUcpwodu1hDuSfkTwvyDPrmgUj_GlH23mI3_dXoHt0RFmz5JE) page.

Is it possible to make a more detailed video using the FOREGROUND_SERVICE_MEDIA_PROJECTION service?

**Comment by andriusalekna** [comment]
@HansCraftsman @Svaike did you manage to resolve this issue?

**Comment by MaximSamolovov** [comment]
> @Svaike @HansCraftsman удалось ли вам решить эту проблему?

Partly. Some of our clients were really helped by the video and description of the process from @Svaike response. But others still get repeated rejections because of FOREGROUND_SERVICE. Moreover, some clients receive repeated rejections after they have successfully passed the review. Literally tonight, 3 clients received a new build update, although they definitely resolved the issue with Google support.
I think the problem is relevant and requires a correct solution.
