### ISSUE TITLE
java.lang.IllegalStateException - DI is not initialized

### ISSUE THREAD

**Issue by andriusalekna** [ondato/ondato-sdk-android#15]
![Screenshot 2024-07-02 at 14 49 24](https://github.com/ondato/ondato-sdk-android/assets/154411783/5549b64e-cc5c-4f3d-8ac6-bcaec09ddf3d)

Not sure is it Crashlytics issue but it is always 2 crashes followed by 2-3 seconds. Attaching logs for both.
My hint would be that app is left in the background while Ondato SDK is running. Maybe activity is destroyed and then after waking up the app it tries to recreate and fails during DI init.
Version: 2.5.4

[de.kurts.sharing_issue_5bf1c82a6196345ce48d333e0a8e3fbf_crash_session_6678FB05002100013CAB361E7C9EB8B9_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16067564/de.kurts.sharing_issue_5bf1c82a6196345ce48d333e0a8e3fbf_crash_session_6678FB05002100013CAB361E7C9EB8B9_DNE_0_v2_stacktrace.txt)
[de.kurts.sharing_issue_5bf1c82a6196345ce48d333e0a8e3fbf_crash_session_6678FB07018400013D25361E7C9EB8B9_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16067565/de.kurts.sharing_issue_5bf1c82a6196345ce48d333e0a8e3fbf_crash_session_6678FB07018400013D25361E7C9EB8B9_DNE_0_v2_stacktrace.txt)

**Comment by ondato-mobile** [comment]
Please try using the latest version.
