### ISSUE TITLE
Unable to test/build your SDK

### ISSUE THREAD

**Issue by edgar-zigis** [ondato/ondato-sdk-android#3]
Hi,

when trying to build 1.8.7 version, gradle build screams this:
`Failed to resolve: cz.adaptech.android:tesseract4android:2.1.0`

I see that you have put the tag for `1.8.8`, but it is not available on your repositories and can't be resolved.
Version `1.8.5` at least builds, but it shows "Enable camera" all the time although camera permission has been given.

**Comment by edvbal** [comment]
please try adding `1.8.8` dependency again
