### ISSUE TITLE
Unable to test/build your SDK (v.2.5.3)

### ISSUE THREAD

**Issue by AtanasHristov12** [ondato/ondato-sdk-android#8]
Hello team,

Could you please investigate the error we encountered with the Android SDK? 

Please track this request:
https://idvs.ondato.com/v1/kyc-identifications/7ab8cb49-cccd-4955-b1c8-c09f3481272a/verification

We've checked and it looks like this request is returning an error and we can't start the process in our mobile app.

We would appreciate it if you could track this request and look into the issue as soon as possible. 

I have attached a video and logs for your reference.

The Android SDK version in question is 2.5.3.

Thank you in advance!

https://github.com/ondato/ondato-sdk-android/assets/166386737/a22de1a3-4ad1-4fbe-ad88-e06641b189f9

[Request details.txt](https://github.com/ondato/ondato-sdk-android/files/15093114/Request.details.txt)

Best Regards,
Atanas Hristov

**Comment by Svaike** [comment]
@AtanasHristov12 was it one time issue or you are getting the same result constantly? We'll try to reproduce the issue with your configuration as the data for the sandbox environment is being deleted after 7 days and we can no longer access it.

Also make sure, that for each new session you generate a new IDV ID. The IDV ID sessions also expire after 24h hours.

**Comment by Svaike** [comment]
Update: we were unable to reproduce the issue with the same configuration. Would you be able to share a new case and include the application logs?

**Comment by edgaras-simanavicius** [comment]
@AtanasHristov12 Hello, we managed to reproduce this with a new device, a fix is on the way.

**Comment by edgaras-simanavicius** [comment]
https://github.com/ondato/ondato-sdk-android/releases/tag/2.5.4
